default: &default
  adapter: postgresql
  username: admin
  password: admin
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: pika_picassa_d

test:
  <<: *default
  database: pika_picassa_t

production:
  <<: *default
  database: pika_picassa_p
